on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_OCI_REG_USER: ${{ github.repository_owner }}
      BUILD_OCI_REG_PASS: ${{ secrets.GITHUB_TOKEN }}
      BUILD_OCI_REG_SERVER: ghcr.io
      BUILD_S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      BUILD_S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      BUILD_S3_ENDPOINT: ams1.vultrobjects.com
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp-contrib/setup-packer@v1
      - name: Init Packer
        run: packer init .
      - name: Run build script
        run: ./scripts/build.sh
